Ext.define('aahaar.constant.ActionType', {
	alias: 'appActionType',
	alternateClassName: 'appActionType',
	statics: {
		ACTION_TYPE_NEW: 'NEW',
		ACTION_TYPE_NEW_ORDER: 'NEW_ORDER',
		ACTION_TYPE_NEW_EXPENSE: 'NEW_EXPENSE',
		ACTION_TYPE_NEW_CATEGORY: 'NEW_CATEGORY',
		
		ACTION_TYPE_LOGIN: 'LOGIN',
		ACTION_TYPE_LOGOUT: 'LOGOUT',
		
		ACTION_TYPE_SELECT: 'SELECT',
		ACTION_TYPE_SELECT_TYPE: 'SELECT_TYPE',
		ACTION_TYPE_SELECT_SALES: 'SELECT_SALES',
		ACTION_TYPE_SELECT_ORDER: 'SELECT_ORDER',
		ACTION_TYPE_SELECT_PRODUCT: 'SELECT_PRODUCT',
		ACTION_TYPE_SELECT_CATEGORY: 'SELECT_CATEGORY',

		ACTION_TYPE_UPDATE: 'UPDATE',
		ACTION_TYPE_UPDATE_ORDER: 'UPDATE_ORDER',
		ACTION_TYPE_UPDATE_EXPENSE: 'UPDATE_EXPENSE',
		ACTION_TYPE_UPDATE_CATEGORY: 'UPDATE_CATEGORY'
		
	}
});